Traceback (most recent call last):
  File "C:\Users\xncxy\AppData\Roaming\Python\Python37\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\xncxy\appdata\local\continuum\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\xncxy\appdata\local\continuum\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\xncxy\appdata\local\continuum\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\xncxy\appdata\local\continuum\anaconda3\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "c:\users\xncxy\appdata\local\continuum\anaconda3\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\xncxy\appdata\local\continuum\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\xncxy\appdata\local\continuum\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cdopt 
import numpy as np
import scipy as sp
from scipy.sparse import csr_matrix, diags
from scipy.sparse.linalg import spsolve
import time
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_3104/11598868.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mcdopt[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mscipy[0m [1;32mas[0m [0msp[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0msparse[0m [1;32mimport[0m [0mcsr_matrix[0m[1;33m,[0m [0mdiags[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0msparse[0m[1;33m.[0m[0mlinalg[0m [1;32mimport[0m [0mspsolve[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'cdopt'
ModuleNotFoundError: No module named 'cdopt'

